### ISSUE TITLE
Beautiful Soup not working properly

### ISSUE THREAD

**Issue by harshit98** [harshit98/Indian-Passport-Tracker#1]
The library is not able to collect data from Indian passport website.

Website: https://portal2.passportindia.gov.in

**Comment by mvgolom** [comment]
Can you give more details on what data do you need to collect?

**Comment by harshit98** [comment]
@mvgolom Hi 👋. I've already written the initial code which will help you get started. The aim is to run the program in the terminal and it should provide result as 'status' of passport.
